### PR TITLE
Add US, songs, led matrix, and some other things

### PR DESCRIPTION
**Pull request by mishafarms**
Scotty,

I have added a lot of code. I am still working on it, But wanted to give you a heads up and get you to start a review. I have tested it on my ESP32 OTTO dev board that I have had setup for a while. It has a US sensor. Buzzer and LED matrix connected. It is not connected to a body so I have not tested the servos.

I still have some gestures to add. I have not started on the noise and battery, but my system has those as well. I will work on these in the next day or so.

As an aside, I have also been working on a version of edublocks-micropython (It is working but I need to add alot, But it does run on my system. I have not been able to get it to work with a version of micropython that has the PSRAM enabled, But I will work on that after everything else.

Let me know what you think. 

Michael

### CODE REVIEW

**Comment by mishafarms** [comment]
Scotty,

    I got all the gestures working.

   Still need to do the ADC for noise and battery.

Michael

**Comment by sfranzyshen** [comment]
excellent 😃

**Comment by sfranzyshen** [comment]
@mishafarms I didn't look before asking but how are you handling battery level? if the esp adc is read internally it will show 3.3v and would be reading after the regulator and not show a true battery level (as it would show 3.3v no matter what) what are your plans for how to power the otto pcb board? did you have a battery connector (in addition to the DC input jack) on the pcb? and if so ... maybe a voltage divider added to the next pcb version to feed the adc with the battery connector voltage from before the regulator ...

**Comment by mishafarms** [comment]
I do have a voltage divider so that at we can read it scaled to 3.3 volts. We may have to play with the resistor values. I do have an external 5V power port as well as usb power and battery.

**Pull request merged**
